Use dice notation for damage
bagelbits/5e-database pull request #210
Opened 2020-07-03 14:08 UTC by ogregoire

## What does this do?
1. Merge the `"damage_dice"` and `"damage_bonus"` fields into one `"damage_dice"` field with [standard dice notation](https://en.wikipedia.org/wiki/Dice_notation).
2. Remove the damage for the net, since its damage is stroked through in the SRD.

## Is there a Github issue this is resolving?
No, not yet

## Here's a fun image for your troubles
![random photo - update me](https://picsum.photos/200)

2020-07-03 14:15 UTC, ogregoire commented
Please note that I'm fully aware of the rule of the critical which doubles the damage dice without bonus (or triples if a Balor inflicts the damage with its longsword), however the data is as it is in the book: "NdX+Y". I believe we should keep it as is and leave the separation of the dice and bonus to the implementation, just like a lot of the rest. Writing a parser is a rather easy task and we could provide examples of parsing rules in the wiki (I gladly could).

2020-07-03 18:58 UTC, bagelbits commented
I think adding examples of parsing rules in the wiki is a really great idea. I know that I've also gotten repeated questions on calculating hit points for monsters. Let me post this up on the discord as well so people know that this is coming.

2020-07-03 19:00 UTC, bagelbits commented
My main concern is that this might be considered a breaking change? Which doesn't mean we shouldn't do it. But I'm not sure if now is a good time to introduce the idea of versioning.

2020-07-03 19:32 UTC, AndruC requested changes
Regression: +0 to hit removed from monsters

2020-07-03 19:32 UTC, AndruC commented on src/5e-SRD-Monsters.json
> +        "desc": "Melee Weapon Attack:  to hit, reach 5 ft., one target. Hit: 1 slashing damage.",
Probably want to check if this was removed elsewhere too.

2020-07-03 19:32 UTC, AndruC commented on src/5e-SRD-Monsters.json
> +        "desc": "Melee Weapon Attack:  to hit, reach 5 ft., one target. Hit: 1 piercing damage.",
Add +0 attack mod back in

2020-07-03 19:32 UTC, AndruC commented on src/5e-SRD-Monsters.json
> +        "desc": "Melee Weapon Attack:  to hit, reach 5 ft., one target. Hit: 1 bludgeoning damage.",
Fix

2020-07-03 19:32 UTC, AndruC commented on src/5e-SRD-Monsters.json
> +        "desc": "Melee Weapon Attack:  to hit, reach 5 ft., one target. Hit: 1 piercing damage.",
Fix

2020-07-03 19:32 UTC, AndruC commented on src/5e-SRD-Monsters.json
> +        "desc": "Melee Weapon Attack:  to hit, reach 5 ft., one creature. Hit: 1 piercing damage.",
Fix

2020-07-03 20:38 UTC, ogregoire commented
@AndruC Nice catch! I fixed all the issues you mentioned and a few others I saw while fixing.

2020-07-09 18:41 UTC, AndruC commented
I'm going to leave the approval to @bagelbits at this point, given the comments on breaking changes and versioning

2020-07-16 16:44 UTC, bagelbits commented
@ogregoire I'll probably merge this in later this evening and close out the versioning stuff I did. My one ask is that either in this PR or a followup, that you add a section to the wiki for parsing rules.

2020-07-16 16:47 UTC, ogregoire commented
@bagelbits I can do that before next week, and this PR can stay open until that is done as well, if you like.

2020-07-17 09:12 UTC, ogregoire commented
Just a small notification to say that [the grammar was added to the wiki](https://github.com/bagelbits/5e-database/wiki/Dice-Notation). Is this what you expected, @bagelbits ?

2020-07-17 18:46 UTC, bagelbits commented
I guess that'll work. Never used ANTLR before though. :D

2020-07-17 19:56 UTC, bagelbits approved these changes
LGTM

2020-07-18 18:23 UTC, merged